### ISSUE TITLE
Code indentation looks bad

### ISSUE THREAD

**Issue by ninjatux** [vigour-io/pliant#4]
An easy way to solve this problem is to use [editorconfig](http://editorconfig.org/) to unify configuration across multiple code editors. If you include a simple `.editorconfig` file in you projects the plugin will configure your editor accordingly.

simple example of `.editorconfig` file:

```
[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 4
charset = utf-8
trim_trailing_whitespace = true
max_line_length = 120
```

**Comment by shawninder** [comment]
@NinjaTux  Which part is badly indented?
I do have my own editor configured..

**Comment by shawninder** [comment]
Or are you talking about using tabs instead of spaces?

**Comment by jimdebeer** [comment]
this is a good solution ;)

**Comment by jimdebeer** [comment]
spaces > tabs for git

**Comment by shawninder** [comment]
Ok, looks like most of use are using "translateTabsToSpaces" so I will do the same.

**Comment by shawninder** [comment]
I made the change in sublime, but now it no longer respects `tab_size: 2`... It's putting 4 spaces everywhere, which is the worst of both worlds :p Anyone know how to solve this?

**Comment by ninjatux** [comment]
not sure if I understood your problem so maybe this is not a solution :p

with Sublime you can specify custom indentation ruler for every kind of file type (same with editorconfig btw).

check [this link](http://www.sublimetext.com/docs/file-type-preferences)

**Comment by shawninder** [comment]
ok I think I've solved this in my editor now. Indentation will get progressively better as I touch the files
